version: "3.1"

services:
  # PHP/Apache Service
  sinapsisvet-api-laravel-gamma:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: sinapsisvet-api-laravel-gamma
    restart: always
    ports:
      - "8072:80"
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sinapsisvet-api-laravel-network

  # MySQL Service
  mysql-gamma:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - sinapsisvet-api-laravel-network

# Docker Networks
networks:
  sinapsisvet-api-laravel-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
