version: "3.1"

services:
  # PHP/Apache Service
  sinapsisvet-api-laravel:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: sinapsisvet-api-laravel
    restart: always
    ports:
      - "8071:80"
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sinapsisvet-api-laravel-network
      - sinapsisvet-shared-network  # Red compartida

  # MySQL Service
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - sinapsisvet-api-laravel-network

  # NGINX Service
  nginx:
    image: nginx:latest
    container_name: sinapsisvet-nginx
    restart: always
    ports:
      - "80:80"  # This exposes NGINX to the VPS on port 80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Configuration for NGINX
      - ./app/:/var/www/app  # Static files, if any
    networks:
      - sinapsisvet-api-laravel-network
      - sinapsisvet-shared-network  # Red compartida

# Docker Networks
networks:
  sinapsisvet-api-laravel-network:
    driver: bridge
  sinapsisvet-shared-network:
    external: true

volumes:
  mysql_data:
    driver: local
