version: "3.1"

services:
  # PHP/Apache Service
  sinapsisvet-api-laravel:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: sinapsisvet-api-laravel
    restart: always
    ports:
      - "8071:80"
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sinapsisvet-api-laravel-network
      - sinapsisvet-shared-network

  # MySQL Service
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - sinapsisvet-api-laravel-network

  # NGINX Service
  nginx:
    image: nginx:latest
    container_name: sinapsisvet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # Puerto para HTTPS
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/:/var/www/app
      - ./docker/certbot/conf:/etc/letsencrypt  # Certificados SSL de Let's Encrypt
      - ./docker/certbot/www:/var/www/certbot  # Carpeta de autenticación para Certbot
      - ./front:/usr/share/nginx/html
      - ./front-desarrollo:/user/share/nginx/html-gamma
    networks:
      - sinapsisvet-api-laravel-network
      - sinapsisvet-shared-network

  # Certbot Service
  certbot:
    image: certbot/certbot
    container_name: sinapsisvet-certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --webroot -w /var/www/certbot -d sinapsisvet.com -d api-desarrollo.sinapsisvet.com --email ezequielm789@gmail.com --agree-tos --non-interactive; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - sinapsisvet-api-laravel-network
      - sinapsisvet-shared-network

# Docker Networks
networks:
  sinapsisvet-api-laravel-network:
    driver: bridge
  sinapsisvet-shared-network:
    external: true

volumes:
  mysql_data:
    driver: local
