<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
class CountriesSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
        ['name' => 'Afganistán', 'iso2' => 'AF', 'phone_code' => '93'],
        ['name' => 'Albania', 'iso2' => 'AL', 'phone_code' => '355'],
        ['name' => 'Alemania', 'iso2' => 'DE', 'phone_code' => '49'],
        ['name' => 'Andorra', 'iso2' => 'AD', 'phone_code' => '376'],
        ['name' => 'Angola', 'iso2' => 'AO', 'phone_code' => '244'],
        ['name' => 'Anguila', 'iso2' => 'AI', 'phone_code' => '1 264'],
        ['name' => 'Antártida', 'iso2' => 'AQ', 'phone_code' => '672'],
        ['name' => 'Antigua y Barbuda', 'iso2' => 'AG', 'phone_code' => '1 268'],
        ['name' => 'Arabia Saudita', 'iso2' => 'SA', 'phone_code' => '966'],
        ['name' => 'Argelia', 'iso2' => 'DZ', 'phone_code' => '213'],
        ['name' => 'Argentina', 'iso2' => 'AR', 'phone_code' => '54'],
        ['name' => 'Armenia', 'iso2' => 'AM', 'phone_code' => '374'],
        ['name' => 'Aruba', 'iso2' => 'AW', 'phone_code' => '297'],
        ['name' => 'Australia', 'iso2' => 'AU', 'phone_code' => '61'],
        ['name' => 'Austria', 'iso2' => 'AT', 'phone_code' => '43'],
        ['name' => 'Azerbaiyán', 'iso2' => 'AZ', 'phone_code' => '994'],
        ['name' => 'Bélgica', 'iso2' => 'BE', 'phone_code' => '32'],
        ['name' => 'Bahamas', 'iso2' => 'BS', 'phone_code' => '1 242'],
        ['name' => 'Bahrein', 'iso2' => 'BH', 'phone_code' => '973'],
        ['name' => 'Bangladesh', 'iso2' => 'BD', 'phone_code' => '880'],
        ['name' => 'Barbados', 'iso2' => 'BB', 'phone_code' => '1 246'],
        ['name' => 'Belice', 'iso2' => 'BZ', 'phone_code' => '501'],
        ['name' => 'Benín', 'iso2' => 'BJ', 'phone_code' => '229'],
        ['name' => 'Bhután', 'iso2' => 'BT', 'phone_code' => '975'],
        ['name' => 'Bielorrusia', 'iso2' => 'BY', 'phone_code' => '375'],
        ['name' => 'Birmania', 'iso2' => 'MM', 'phone_code' => '95'],
        ['name' => 'Bolivia', 'iso2' => 'BO', 'phone_code' => '591'],
        ['name' => 'Bosnia y Herzegovina', 'iso2' => 'BA', 'phone_code' => '387'],
        ['name' => 'Botsuana', 'iso2' => 'BW', 'phone_code' => '267'],
        ['name' => 'Brasil', 'iso2' => 'BR', 'phone_code' => '55'],
        ['name' => 'Brunéi', 'iso2' => 'BN', 'phone_code' => '673'],
        ['name' => 'Bulgaria', 'iso2' => 'BG', 'phone_code' => '359'],
        ['name' => 'Burkina Faso', 'iso2' => 'BF', 'phone_code' => '226'],
        ['name' => 'Burundi', 'iso2' => 'BI', 'phone_code' => '257'],
        ['name' => 'Cabo Verde', 'iso2' => 'CV', 'phone_code' => '238'],
        ['name' => 'Camboya', 'iso2' => 'KH', 'phone_code' => '855'],
        ['name' => 'Camerún', 'iso2' => 'CM', 'phone_code' => '237'],
        ['name' => 'Canadá', 'iso2' => 'CA', 'phone_code' => '1'],
        ['name' => 'Chad', 'iso2' => 'TD', 'phone_code' => '235'],
        ['name' => 'Chile', 'iso2' => 'CL', 'phone_code' => '56'],
        ['name' => 'China', 'iso2' => 'CN', 'phone_code' => '86'],
        ['name' => 'Chipre', 'iso2' => 'CY', 'phone_code' => '357'],
        ['name' => 'Ciudad del Vaticano', 'iso2' => 'VA', 'phone_code' => '39'],
        ['name' => 'Colombia', 'iso2' => 'CO', 'phone_code' => '57'],
        ['name' => 'Comoras', 'iso2' => 'KM', 'phone_code' => '269'],
        ['name' => 'República del Congo', 'iso2' => 'CG', 'phone_code' => '242'],
        ['name' => 'República Democrática del Congo', 'iso2' => 'CD', 'phone_code' => '243'],
        ['name' => 'Corea del Norte', 'iso2' => 'KP', 'phone_code' => '850'],
        ['name' => 'Corea del Sur', 'iso2' => 'KR', 'phone_code' => '82'],
        ['name' => 'Costa de Marfil', 'iso2' => 'CI', 'phone_code' => '225'],
        ['name' => 'Costa Rica', 'iso2' => 'CR', 'phone_code' => '506'],
        ['name' => 'Croacia', 'iso2' => 'HR', 'phone_code' => '385'],
        ['name' => 'Cuba', 'iso2' => 'CU', 'phone_code' => '53'],
        ['name' => 'Curazao', 'iso2' => 'CW', 'phone_code' => '5999'],
        ['name' => 'Dinamarca', 'iso2' => 'DK', 'phone_code' => '45'],
        ['name' => 'Dominica', 'iso2' => 'DM', 'phone_code' => '1 767'],
        ['name' => 'Ecuador', 'iso2' => 'EC', 'phone_code' => '593'],
        ['name' => 'Egipto', 'iso2' => 'EG', 'phone_code' => '20'],
        ['name' => 'El Salvador', 'iso2' => 'SV', 'phone_code' => '503'],
        ['name' => 'Emiratos Árabes Unidos', 'iso2' => 'AE', 'phone_code' => '971'],
        ['name' => 'Eritrea', 'iso2' => 'ER', 'phone_code' => '291'],
        ['name' => 'Eslovaquia', 'iso2' => 'SK', 'phone_code' => '421'],
        ['name' => 'Eslovenia', 'iso2' => 'SI', 'phone_code' => '386'],
        ['name' => 'España', 'iso2' => 'ES', 'phone_code' => '34'],
        ['name' => 'Estados Unidos de América', 'iso2' => 'US', 'phone_code' => '1'],
        ['name' => 'Estonia', 'iso2' => 'EE', 'phone_code' => '372'],
        ['name' => 'Etiopía', 'iso2' => 'ET', 'phone_code' => '251'],
        ['name' => 'Filipinas', 'iso2' => 'PH', 'phone_code' => '63'],
        ['name' => 'Finlandia', 'iso2' => 'FI', 'phone_code' => '358'],
        ['name' => 'Fiyi', 'iso2' => 'FJ', 'phone_code' => '679'],
        ['name' => 'Francia', 'iso2' => 'FR', 'phone_code' => '33'],
        ['name' => 'Gabón', 'iso2' => 'GA', 'phone_code' => '241'],
        ['name' => 'Gambia', 'iso2' => 'GM', 'phone_code' => '220'],
        ['name' => 'Georgia', 'iso2' => 'GE', 'phone_code' => '995'],
        ['name' => 'Ghana', 'iso2' => 'GH', 'phone_code' => '233'],
        ['name' => 'Gibraltar', 'iso2' => 'GI', 'phone_code' => '350'],
        ['name' => 'Granada', 'iso2' => 'GD', 'phone_code' => '1 473'],
        ['name' => 'Grecia', 'iso2' => 'GR', 'phone_code' => '30'],
        ['name' => 'Groenlandia', 'iso2' => 'GL', 'phone_code' => '299'],
        ['name' => 'Guadalupe', 'iso2' => 'GP', 'phone_code' => '590'],
        ['name' => 'Guam', 'iso2' => 'GU', 'phone_code' => '1 671'],
        ['name' => 'Guatemala', 'iso2' => 'GT', 'phone_code' => '502'],
        ['name' => 'Guayana Francesa', 'iso2' => 'GF', 'phone_code' => '594'],
        ['name' => 'Guernsey', 'iso2' => 'GG', 'phone_code' => '44'],
        ['name' => 'Guinea', 'iso2' => 'GN', 'phone_code' => '224'],
        ['name' => 'Guinea-Bisáu', 'iso2' => 'GW', 'phone_code' => '245'],
        ['name' => 'Guinea Ecuatorial', 'iso2' => 'GQ', 'phone_code' => '240'],
        ['name' => 'Guyana', 'iso2' => 'GY', 'phone_code' => '592'],
        ['name' => 'Haití', 'iso2' => 'HT', 'phone_code' => '509'],
        ['name' => 'Honduras', 'iso2' => 'HN', 'phone_code' => '504'],
        ['name' => 'Hong Kong', 'iso2' => 'HK', 'phone_code' => '852'],
        ['name' => 'Hungría', 'iso2' => 'HU', 'phone_code' => '36'],
        ['name' => 'India', 'iso2' => 'IN', 'phone_code' => '91'],
        ['name' => 'Indonesia', 'iso2' => 'ID', 'phone_code' => '62'],
        ['name' => 'Irak', 'iso2' => 'IQ', 'phone_code' => '964'],
        ['name' => 'Irán', 'iso2' => 'IR', 'phone_code' => '98'],
        ['name' => 'Irlanda', 'iso2' => 'IE', 'phone_code' => '353'],
        ['name' => 'Isla Bouvet', 'iso2' => 'BV', 'phone_code' => '47'],
        ['name' => 'Isla de Man', 'iso2' => 'IM', 'phone_code' => '44'],
        ['name' => 'Isla Heard e Islas McDonald', 'iso2' => 'HM', 'phone_code' => '672'],
        ['name' => 'Islas Caimán', 'iso2' => 'KY', 'phone_code' => '1 345'],
        ['name' => 'Islas Cocos', 'iso2' => 'CC', 'phone_code' => '61'],
        ['name' => 'Islas Cook', 'iso2' => 'CK', 'phone_code' => '682'],
        ['name' => 'Islas Feroe', 'iso2' => 'FO', 'phone_code' => '298'],
        ['name' => 'Islas Georgias del Sur y Sandwich del Sur', 'iso2' => 'GS', 'phone_code' => '500'],
        ['name' => 'Islas Malvinas', 'iso2' => 'FK', 'phone_code' => '500'],
        ['name' => 'Islas Marianas del Norte', 'iso2' => 'MP', 'phone_code' => '1 670'],
        ['name' => 'Islas Marshall', 'iso2' => 'MH', 'phone_code' => '692'],
        ['name' => 'Islas Pitcairn', 'iso2' => 'PN', 'phone_code' => '64'],
        ['name' => 'Islas Salomón', 'iso2' => 'SB', 'phone_code' => '677'],
        ['name' => 'Islas Turcas y Caicos', 'iso2' => 'TC', 'phone_code' => '1 649'],
        ['name' => 'Islas Vírgenes Británicas', 'iso2' => 'VG', 'phone_code' => '1 284'],
        ['name' => 'Islas Vírgenes de los Estados Unidos', 'iso2' => 'VI', 'phone_code' => '1 340'],
        ['name' => 'Israel', 'iso2' => 'IL', 'phone_code' => '972'],
        ['name' => 'Italia', 'iso2' => 'IT', 'phone_code' => '39'],
        ['name' => 'Jamaica', 'iso2' => 'JM', 'phone_code' => '1 876'],
        ['name' => 'Japón', 'iso2' => 'JP', 'phone_code' => '81'],
        ['name' => 'Jersey', 'iso2' => 'JE', 'phone_code' => '44'],
        ['name' => 'Jordania', 'iso2' => 'JO', 'phone_code' => '962'],
        ['name' => 'Kazajistán', 'iso2' => 'KZ', 'phone_code' => '7'],
        ['name' => 'Kenia', 'iso2' => 'KE', 'phone_code' => '254'],
        ['name' => 'Kirguistán', 'iso2' => 'KG', 'phone_code' => '996'],
        ['name' => 'Kiribati', 'iso2' => 'KI', 'phone_code' => '686'],
        ['name' => 'Kuwait', 'iso2' => 'KW', 'phone_code' => '965'],
        ['name' => 'Laos', 'iso2' => 'LA', 'phone_code' => '856'],
        ['name' => 'Lesoto', 'iso2' => 'LS', 'phone_code' => '266'],
        ['name' => 'Letonia', 'iso2' => 'LV', 'phone_code' => '371'],
        ['name' => 'Líbano', 'iso2' => 'LB', 'phone_code' => '961'],
        ['name' => 'Liberia', 'iso2' => 'LR', 'phone_code' => '231'],
        ['name' => 'Libia', 'iso2' => 'LY', 'phone_code' => '218'],
        ['name' => 'Liechtenstein', 'iso2' => 'LI', 'phone_code' => '423'],
        ['name' => 'Lituania', 'iso2' => 'LT', 'phone_code' => '370'],
        ['name' => 'Luxemburgo', 'iso2' => 'LU', 'phone_code' => '352'],
        ['name' => 'Macao', 'iso2' => 'MO', 'phone_code' => '853'],
        ['name' => 'Macedonia del Norte', 'iso2' => 'MK', 'phone_code' => '389'],
        ['name' => 'Madagascar', 'iso2' => 'MG', 'phone_code' => '261'],
        ['name' => 'Malasia', 'iso2' => 'MY', 'phone_code' => '60'],
        ['name' => 'Malawi', 'iso2' => 'MW', 'phone_code' => '265'],
        ['name' => 'Maldivas', 'iso2' => 'MV', 'phone_code' => '960'],
        ['name' => 'Malí', 'iso2' => 'ML', 'phone_code' => '223'],
        ['name' => 'Malta', 'iso2' => 'MT', 'phone_code' => '356'],
        ['name' => 'Marruecos', 'iso2' => 'MA', 'phone_code' => '212'],
        ['name' => 'Martinica', 'iso2' => 'MQ', 'phone_code' => '596'],
        ['name' => 'Mauricio', 'iso2' => 'MU', 'phone_code' => '230'],
        ['name' => 'Mauritania', 'iso2' => 'MR', 'phone_code' => '222'],
        ['name' => 'Mayotte', 'iso2' => 'YT', 'phone_code' => '262'],
        ['name' => 'México', 'iso2' => 'MX', 'phone_code' => '52'],
        ['name' => 'Micronesia', 'iso2' => 'FM', 'phone_code' => '691'],
        ['name' => 'Moldavia', 'iso2' => 'MD', 'phone_code' => '373'],
        ['name' => 'Mónaco', 'iso2' => 'MC', 'phone_code' => '377'],
        ['name' => 'Mongolia', 'iso2' => 'MN', 'phone_code' => '976'],
        ['name' => 'Montenegro', 'iso2' => 'ME', 'phone_code' => '382'],
        ['name' => 'Montserrat', 'iso2' => 'MS', 'phone_code' => '1 664'],
        ['name' => 'Mozambique', 'iso2' => 'MZ', 'phone_code' => '258'],
        ['name' => 'Namibia', 'iso2' => 'NA', 'phone_code' => '264'],
        ['name' => 'Nauru', 'iso2' => 'NR', 'phone_code' => '674'],
        ['name' => 'Nepal', 'iso2' => 'NP', 'phone_code' => '977'],
        ['name' => 'Nicaragua', 'iso2' => 'NI', 'phone_code' => '505'],
        ['name' => 'Níger', 'iso2' => 'NE', 'phone_code' => '227'],
        ['name' => 'Nigeria', 'iso2' => 'NG', 'phone_code' => '234'],
        ['name' => 'Niue', 'iso2' => 'NU', 'phone_code' => '683'],
        ['name' => 'Noruega', 'iso2' => 'NO', 'phone_code' => '47'],
        ['name' => 'Nueva Caledonia', 'iso2' => 'NC', 'phone_code' => '687'],
        ['name' => 'Nueva Zelanda', 'iso2' => 'NZ', 'phone_code' => '64'],
        ['name' => 'Omán', 'iso2' => 'OM', 'phone_code' => '968'],
        ['name' => 'Países Bajos', 'iso2' => 'NL', 'phone_code' => '31'],
        ['name' => 'Pakistán', 'iso2' => 'PK', 'phone_code' => '92'],
        ['name' => 'Palaos', 'iso2' => 'PW', 'phone_code' => '680'],
        ['name' => 'Palestina', 'iso2' => 'PS', 'phone_code' => '970'],
        ['name' => 'Panamá', 'iso2' => 'PA', 'phone_code' => '507'],
        ['name' => 'Papúa Nueva Guinea', 'iso2' => 'PG', 'phone_code' => '675'],
        ['name' => 'Paraguay', 'iso2' => 'PY', 'phone_code' => '595'],
        ['name' => 'Perú', 'iso2' => 'PE', 'phone_code' => '51'],
        ['name' => 'Polinesia Francesa', 'iso2' => 'PF', 'phone_code' => '689'],
        ['name' => 'Polonia', 'iso2' => 'PL', 'phone_code' => '48'],
        ['name' => 'Portugal', 'iso2' => 'PT', 'phone_code' => '351'],
        ['name' => 'Puerto Rico', 'iso2' => 'PR', 'phone_code' => '1'],
        ['name' => 'Qatar', 'iso2' => 'QA', 'phone_code' => '974'],
        ['name' => 'Reino Unido', 'iso2' => 'GB', 'phone_code' => '44'],
        ['name' => 'República Centroafricana', 'iso2' => 'CF', 'phone_code' => '236'],
        ['name' => 'República Checa', 'iso2' => 'CZ', 'phone_code' => '420'],
        ['name' => 'República Democrática del Congo', 'iso2' => 'CD', 'phone_code' => '243'],
        ['name' => 'República Dominicana', 'iso2' => 'DO', 'phone_code' => '1 809'],
        ['name' => 'Reunión', 'iso2' => 'RE', 'phone_code' => '262'],
        ['name' => 'Ruanda', 'iso2' => 'RW', 'phone_code' => '250'],
        ['name' => 'Rumanía', 'iso2' => 'RO', 'phone_code' => '40'],
        ['name' => 'Rusia', 'iso2' => 'RU', 'phone_code' => '7'],
        ['name' => 'Samoa', 'iso2' => 'WS', 'phone_code' => '685'],
        ['name' => 'Samoa Americana', 'iso2' => 'AS', 'phone_code' => '1 684'],
        ['name' => 'San Bartolomé', 'iso2' => 'BL', 'phone_code' => '590'],
        ['name' => 'San Cristóbal y Nieves', 'iso2' => 'KN', 'phone_code' => '1 869'],
        ['name' => 'San Marino', 'iso2' => 'SM', 'phone_code' => '378'],
        ['name' => 'San Martín', 'iso2' => 'MF', 'phone_code' => '590'],
        ['name' => 'San Pedro y Miquelón', 'iso2' => 'PM', 'phone_code' => '508'],
        ['name' => 'San Vicente y las Granadinas', 'iso2' => 'VC', 'phone_code' => '1 784'],
        ['name' => 'Santa Elena', 'iso2' => 'SH', 'phone_code' => '290'],
        ['name' => 'Santa Lucía', 'iso2' => 'LC', 'phone_code' => '1 758'],
        ['name' => 'Santo Tomé y Príncipe', 'iso2' => 'ST', 'phone_code' => '239'],
        ['name' => 'Senegal', 'iso2' => 'SN', 'phone_code' => '221'],
        ['name' => 'Serbia', 'iso2' => 'RS', 'phone_code' => '381'],
        ['name' => 'Seychelles', 'iso2' => 'SC', 'phone_code' => '248'],
        ['name' => 'Sierra Leona', 'iso2' => 'SL', 'phone_code' => '232'],
        ['name' => 'Singapur', 'iso2' => 'SG', 'phone_code' => '65'],
        ['name' => 'Siria', 'iso2' => 'SY', 'phone_code' => '963'],
        ['name' => 'Somalia', 'iso2' => 'SO', 'phone_code' => '252'],
        ['name' => 'Sri Lanka', 'iso2' => 'LK', 'phone_code' => '94'],
        ['name' => 'Suazilandia', 'iso2' => 'SZ', 'phone_code' => '268'],
        ['name' => 'Sudáfrica', 'iso2' => 'ZA', 'phone_code' => '27'],
        ['name' => 'Sudán', 'iso2' => 'SD', 'phone_code' => '249'],
        ['name' => 'Sudán del Sur', 'iso2' => 'SS', 'phone_code' => '211'],
        ['name' => 'Suecia', 'iso2' => 'SE', 'phone_code' => '46'],
        ['name' => 'Suiza', 'iso2' => 'CH', 'phone_code' => '41'],
        ['name' => 'Surinam', 'iso2' => 'SR', 'phone_code' => '597'],
        ['name' => 'Svalbard y Jan Mayen', 'iso2' => 'SJ', 'phone_code' => '47'],
        ['name' => 'Tailandia', 'iso2' => 'TH', 'phone_code' => '66'],
        ['name' => 'Taiwán', 'iso2' => 'TW', 'phone_code' => '886'],
        ['name' => 'Tanzania', 'iso2' => 'TZ', 'phone_code' => '255'],
        ['name' => 'Tayikistán', 'iso2' => 'TJ', 'phone_code' => '992'],
        ['name' => 'Territorio Británico del Océano Índico', 'iso2' => 'IO', 'phone_code' => '246'],
        ['name' => 'Territorios Australes y Antárticas Franceses', 'iso2' => 'TF', 'phone_code' => '262'],
        ['name' => 'Timor Oriental', 'iso2' => 'TL', 'phone_code' => '670'],
        ['name' => 'Togo', 'iso2' => 'TG', 'phone_code' => '228'],
        ['name' => 'Tokelau', 'iso2' => 'TK', 'phone_code' => '690'],
        ['name' => 'Tonga', 'iso2' => 'TO', 'phone_code' => '676'],
        ['name' => 'Trinidad y Tobago', 'iso2' => 'TT', 'phone_code' => '1 868'],
        ['name' => 'Túnez', 'iso2' => 'TN', 'phone_code' => '216'],
        ['name' => 'Turkmenistán', 'iso2' => 'TM', 'phone_code' => '993'],
        ['name' => 'Turquía', 'iso2' => 'TR', 'phone_code' => '90'],
        ['name' => 'Tuvalu', 'iso2' => 'TV', 'phone_code' => '688'],
        ['name' => 'Ucrania', 'iso2' => 'UA', 'phone_code' => '380'],
        ['name' => 'Uganda', 'iso2' => 'UG', 'phone_code' => '256'],
        ['name' => 'Uruguay', 'iso2' => 'UY', 'phone_code' => '598'],
        ['name' => 'Uzbekistán', 'iso2' => 'UZ', 'phone_code' => '998'],
        ['name' => 'Vanuatu', 'iso2' => 'VU', 'phone_code' => '678'],
        ['name' => 'Vaticano', 'iso2' => 'VA', 'phone_code' => '379'],
        ['name' => 'Venezuela', 'iso2' => 'VE', 'phone_code' => '58'],
        ['name' => 'Vietnam', 'iso2' => 'VN', 'phone_code' => '84'],
        ['name' => 'Wallis y Futuna', 'iso2' => 'WF', 'phone_code' => '681'],
        ['name' => 'Yemen', 'iso2' => 'YE', 'phone_code' => '967'],
        ['name' => 'Yibuti', 'iso2' => 'DJ', 'phone_code' => '253'],
        ['name' => 'Zambia', 'iso2' => 'ZM', 'phone_code' => '260'],
        ['name' => 'Zimbabue', 'iso2' => 'ZW', 'phone_code' => '263']
        ]);  
    
    }
}
